site_name: Systemgym
theme:
  name: material
  palette:
    primary: 'yellow'
    accent: 'light blue'
nav:
  - Sobre el Proyecto:
      - Descripción: about.md
      - Integrantes: integrantes.md
  - Systemgym: systemgym.md

  - Administrador Guia:
      - Login: administrador/login.md 
      - Dashboard: administrador/dashboard.md
      - Clientes: administrador/clientes.md 
      - Membresias: administrador/membresias.md 
      - Tarifas: administrador/tarifas.md 
      - Inscripcion: administrador/inscripcion.md 
      - Suscripcion: administrador/suscripcion.md 
      - Suscripcion desactivar: administrador/Suscripcion_Desactivar.md
      - Pagos: administrador/pagos.md 
      - Egresos: administrador/egresos.md 
      - Reportes: administrador/reportes.md 
      - Reporte Ingreso: administrador/reporte_ingreso.md 
      - Reporte Suscripciones Activas: administrador/reporte_suscripciones_activas.md 

      - ActualizarImagen: administrador/Actualizar_imagen.md


  - Cliente Guia:
      - Login: cliente/login.md 
      - ActualizarImagen: cliente/Actualizar_imagen.md
      


  - Contacto: contacto.md